### PR TITLE
Fixed: config.ru evaluated twice

### PR DESCRIPTION
**Pull request by kukushkin**
This PR fixes a problem with config.ru evaluated twice on startup. The cause of it was #rack object evaluated once in the scope of Ripl::Rack::Commands and then in global scope.

To reproduce:

```
# config.ru
puts "config.ru evaluated <= !!!"

run lambda { |env| [200, {}, ["OK"]] }
```

```
$ ripl rack
config.ru evaluated <= !!!
Loading development environment (Rack 1.2)
>> rack
config.ru evaluated <= !!!
...
```

This can lead to undesired behavior. In my project the whole middleware stack was loaded twice. Yuck!

### CODE REVIEW

**Comment by cldwalker** [comment]
I'm not able to reproduce double-loading in 1.9.x or 2.1.0. If it is in one of those versions, I'll need a sample app to reproduce. If it is another ruby version, I can give it another try. rack version would also help.

**Comment by kukushkin** [comment]
I can confirm it for ruby 1.9.3-p484, 2.0.0-p353 and 2.1.0-p0.
Rack and ripl gems installed:
- rack (1.5.2)
- ripl (0.7.0)
- ripl-rack (0.2.0)

Steps to reproduce:

1) In an empty folder create `config.ru` with following contents:

``` ruby
# config.ru
puts "config.ru evaluated <= !!!"

run lambda { |env| [200, {}, ["OK"]] }
```

2) In this folder launch ripl-rack:

```
$ ripl rack
config.ru evaluated <= !!!
Loading development environment (Rack 1.2)
>> 
```

Notice that config.ru is evaluated on startup.

3) Run any rack command (access rack object, or test-send any request to Rack application)

```
>> rack
config.ru evaluated <= !!!
=> ...
```

Notice that config.ru is evaluated for the second time.

**Comment by kukushkin** [comment]
PS. closed PR accidentally

**Comment by cldwalker** [comment]
Thanks for more details. Confirmed. Will be merging and releasing

**Pull request merged**
